import type { Metadata } from "next";
import { ArrowLeft, Check, Code2, ExternalLink } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import ArchitectureDiagram from "@/components/ArchitectureDiagram";
import Footer from "@/components/Footer";
import MediaFrame from "@/components/MediaFrame";
import Nav from "@/components/Nav";
import { getProject, projects } from "@/data/projects";
export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const project = getProject((await params).slug); return project ? { title: project.title, description: project.summary } : {}; }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) { const project = getProject((await params).slug); if (!project) notFound(); return <><Nav /><main><header className="case-head site-container"><Link className="back-link" href="/projects"><ArrowLeft size={14} /> All projects</Link><p className="page-index">{project.eyebrow}</p><h1>{project.title}</h1><p>{project.summary}</p><div className="case-tech">{project.technology.map((item) => <span key={item}>{item}</span>)}</div><MediaFrame media={project.featuredMedia} priority className="case-hero-media" /></header><div className="site-container case-body">{project.incomplete && <aside className="todo-note">This project intentionally contains TODO placeholders in <code>data/projects.ts</code>. Replace them only with verified details.</aside>}<CaseSection title="Overview"><p className="case-lede">{project.origin}</p></CaseSection><CaseSection title="Problem"><p className="case-lede">{project.problem}</p></CaseSection><CaseSection title="What I built"><BulletList items={project.built} /></CaseSection><CaseSection title="Architecture"><ArchitectureDiagram nodes={project.architecture} /></CaseSection><CaseSection title="Technical challenges"><BulletList items={project.challenges} /></CaseSection><CaseSection title="Key features"><BulletList items={project.features} /></CaseSection><CaseSection title="What I learned"><BulletList items={project.learnings} /></CaseSection><CaseSection title="Screenshots / demo"><div className="case-gallery">{project.gallery.length ? project.gallery.map((media) => <MediaFrame media={media} className="gallery-media" key={media.src} />) : <MediaFrame className="gallery-media" />}</div></CaseSection><section className="case-links">{project.githubUrl ? <a href={project.githubUrl}><Code2 size={15} /> GitHub</a> : <span><Code2 size={15} /> Repository not public</span>}{project.demoUrl && <a href={project.demoUrl}>Demo <ExternalLink size={14} /></a>}</section></div></main><Footer /></>; }
function CaseSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="case-section"><h2>{title}</h2><div>{children}</div></section>; }
function BulletList({ items }: { items: string[] }) { return <ul className="case-list">{items.map((item) => <li key={item}><Check size={14} />{item}</li>)}</ul>; }
